### ISSUE TITLE
Not compatible with current pfUI builds?

### ISSUE THREAD

**Issue by byaka** [Road-block/DragonOverlay#1]

**Comment by Road-block** [comment]
Yeah this was made for fun off a forum request months ago. I doubt it worked for very long.  
I might revisit it at some point to make it work with current pfUI.

**Comment by byaka** [comment]
Hope u fine time for fix this, really missed feature in pfui

**Comment by Road-block** [comment]
Fixed in https://github.com/Road-block/DragonOverlay/commit/fa38bfdfa34fc1b9c03a0e42f660f4b415582865

**Comment by byaka** [comment]
thx
